### ISSUE TITLE
Active items get saved only after the next mint and list

### ISSUE THREAD

**Issue by andyts93** [PatrickAlphaC/nextjs-nft-marketplace-moralis-fcc#1]
I've set up Moralis as you described in the README but I have a problem, event sync works well but with a strange delay: ActiveItem are saved only after another mint and list.
For example:
I mint the token 0, I get a record in the ItemListed table but not in the ActiveItem one
I mint the token 1, I get a record in the ItemListed and the token 0 is saved in the ActiveItem one

Any suggestion?

**Comment by PatrickAlphaC** [comment]
Damn, I haven't even made the video for this yet!

You need to mine an extra block after every transaction - our cloud functions only activate after a transition is `confirmed`, and need at least one additional block confirmation. The `mint-and-list-item.js` should have a `mineBlocks` function where it mines an additional block.

Do you have it?

**Comment by andyts93** [comment]
@PatrickAlphaC oh I get it, thanks! Nope I don't have it, I was using the code from the blog post as reference, the `moveBlock` is not mentioned, I forgot to check the repo.
So I should use this function only on the local dev chain, right?

Anyway, great tutorial, thank you!
