### ISSUE TITLE
Setup your Cloud functions

### ISSUE THREAD

**Issue by mazhar11-cou** [PatrickAlphaC/nextjs-nft-marketplace-moralis-fcc#11]
It has typing mistake it will be ```yarn ``` instead of ```yarm```

**Comment by PatrickAlphaC** [comment]
Oh! Thank you!

Can you make a PR to fix?

**Comment by mazhar11-cou** [comment]
> Oh! Thank you!
> 
> Can you make a PR to fix?

I do that. You can add that.
