### ISSUE TITLE
web3 react react-dom moralis react-moralis package installation problem

### ISSUE THREAD

**Issue by LouCse59** [PatrickAlphaC/nextjs-nft-marketplace-moralis-fcc#5]
Moralis still unknown word even if I install the package yarn add web3 react react-dom moralis react-moralis
If someone had the same problem ?
Best

**Comment by PatrickAlphaC** [comment]
Closing for now.

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
